apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ostad-ui-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: chat.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ostad-ui-service
                port:
                  number: 5173
